version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - setup_remote_docker
      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          docker version
      # - run:
      #     name: Install Docker client
      #     command: |
      #       set -x
      #       VER="17.03.0-ce"
      #       curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
      #       tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #       mv /tmp/docker/* /usr/bin
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t us.gcr.io/test-cluster-174217/demoapp:$TAG .
      # docker login -u $DOCKER_USER -p $DOCKER_PASS
      # docker push CircleCI-Public/circleci-demo-docker:$TAG
  test:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          name: Test
          command: echo "this is where i am running a test"
      - run:
          name: Make the artifacts
          command: echo "I am an artifact" > artifact.txt
      - store_artifacts:
          path: artifact.txt
          prefix: artifact-prefix
  deploy:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "this is the part where I deploy."

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
